# Generated by Django 6.0.1 on 2026-03-05 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="architecture_image",
            field=models.ImageField(
                blank=True,
                help_text="Фото для секції Architecture (внизу)",
                null=True,
                upload_to="projects/",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="card_button_text",
            field=models.CharField(
                blank=True,
                default="View Project",
                help_text="Текст кнопки на візитці",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="card_short_description",
            field=models.TextField(
                blank=True, default="", help_text="Короткий опис для візитки проекту"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="intro_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Опис для intro секції (якщо порожнє, використовується description)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="intro_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Заголовок intro секції (якщо порожнє, використовується назва проекту)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="phase01_button_text",
            field=models.CharField(
                blank=True,
                default="Explore Project",
                help_text="Текст кнопки Phase 01",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="phase01_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Опис Phase 01 (якщо порожнє, використовується details)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="phase01_feature1",
            field=models.CharField(
                blank=True,
                default="High-Performance Architecture",
                help_text="Перша перевага",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="phase01_feature2",
            field=models.CharField(
                blank=True,
                default="Modern Development Stack",
                help_text="Друга перевага",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="phase01_subtitle",
            field=models.CharField(
                blank=True,
                default="PROJECT OVERVIEW",
                help_text="Підзаголовок Phase 01",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="phase01_title",
            field=models.CharField(
                blank=True,
                default="Phase 01",
                help_text="Заголовок Phase 01",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="phase02_description",
            field=models.TextField(
                blank=True,
                default="Built on a foundation of reliability and scale. Our choice of technologies reflects a commitment to a developer-first experience and lightning-fast performance across all platforms.",
                help_text="Опис Phase 02",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="phase02_subtitle",
            field=models.CharField(
                blank=True,
                default="TECH STACK",
                help_text="Підзаголовок Phase 02",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="phase02_title",
            field=models.CharField(
                blank=True,
                default="Phase 02",
                help_text="Заголовок Phase 02",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Головне фото (візитка) для картки проекту",
                null=True,
                upload_to="projects/",
            ),
        ),
        migrations.CreateModel(
            name="ProjectMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Фото"), ("video", "Відео")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Фото (якщо media_type = image)",
                        null=True,
                        upload_to="projects/media/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="URL відео (YouTube, Vimeo тощо) - якщо media_type = video. Використовуйте embed URL",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Порядок відображення в слайдері"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="website.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TechStackItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Назва технології", max_length=100),
                ),
                (
                    "description",
                    models.CharField(help_text="Опис технології", max_length=200),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Порядок відображення"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tech_stack_items",
                        to="website.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
